### ISSUE TITLE
Google Analytics Tracking

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/actionwidget#15]
@VonSub can you get the guys what they need here?

@KristofVanstappen can you then implement?

**Comment by VonSub** [comment]
sent the code to @KristofVanstappen

**Comment by VonSub** [comment]
we'll test in on staging but should after testing only be implemented on production environment.

**Comment by ken-de-moor** [comment]
Awaiting feedback for referral_calltoaction project before work on this is continued
