### ISSUE TITLE
We need to link this to 3Bot connect

### ISSUE THREAD

**Issue by Sacha96** [threefoldtech/actionwidget#16]
<img width="762" alt="Screenshot 2020-04-02 at 17 16 26" src="https://user-images.githubusercontent.com/54844940/78266173-b62e5f00-7505-11ea-998e-d9724c11de0e.png">

**Comment by jdelrue** [comment]
This is done by the email. When people tick the box, they will receive an email for registering using 3botconnect. This was discussed yesterday and https://github.com/threefoldtech/actionwidget/issues/4 was created
