### ISSUE TITLE
Text for emails

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/actionwidget#4]
we still need texts for the emails

we send an email:
- to join the referral program
- to install 3bot_connect (should include play and appstore buttons as on the widget)

**Comment by samtaggart** [comment]
Plus an email about TFT, if they check that box.

**Comment by jdelrue** [comment]
Updates?

**Comment by Sacha96** [comment]
can check emails here docs.google.com/document/d/1HFv3ETH6iZa2QvyGeM1gBEcnSYvRcP-kdlKx2K3nq4k/edit
